### ISSUE TITLE
Crash: `StackOverflowError`

### ISSUE THREAD

**Issue by Krutoy242** [jbredwards/Fluidlogged-API#141]
**Describe the bug**
At random intervals, this crash happens:

```less
java.lang.StackOverflowError
    at java.security.AccessController.doPrivileged(Native Method)
    [...]
    at net.minecraft.world.World.setBlockState(World.java:425)
    at git.jbredwards.fluidlogged_api.mod.asm.plugins.vanilla.block.PluginBlockDynamicLiquid$Hooks.flowInto(PluginBlockDynamicLiquid.java:247)
    [...]
```

The place where this happens:

![image](https://user-images.githubusercontent.com/936618/210063752-7eb82462-5f39-47d7-8050-35e8273e743a.png)

**Logs**
[crash-2022-12-26_21.24.13-server.txt](https://github.com/jbredwards/Fluidlogged-API/files/10324366/crash-2022-12-26_21.24.13-server.txt)

**Additional context**
This happens on `E2E-E` modpack, for one of players.
Fluidlogged-API version: `v1.9.0.4`.

**Comment by jbredwards** [comment]
This looks very similar to a crash I fixed in v1.9.0.5, try updating fluidlogged api and see if that fixes the issue.

**Comment by Krutoy242** [comment]
After 4 hours of playing, crash didn't occur. Seems like it fixed, thanks!

I didn't saw `fix: stackOverflow` in patch notes, so though this wasn't fixed.
