### ISSUE TITLE
mixin crash server side

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#21]
just got round to testing this on my server, sadly it crashes. i think its got something to do with sledgehammers mixin patch but its odd because im using sledgehammer on both client and server with the same config and its fine on the client side.

https://pastebin.com/71wFV262

**Comment by jbredwards** [comment]
fixed in v1.5!

**Comment by xemnes** [comment]
sadly still seems to be happening server side https://pastebin.com/8egvhH7y

**Comment by jbredwards** [comment]
I can't recreate this, but I think I fixed it in v1.5.1.

**Comment by xemnes** [comment]
hmm, new error it seems https://pastebin.com/iAG0PaPZ
i wonder why mine is failing catastrophically.

**Comment by jbredwards** [comment]
try [this](https://cdn.discordapp.com/attachments/785959414632939571/863648606333829130/Fluidlogged-API-v1.5.1-mc1.12.2.jar)?

**Comment by xemnes** [comment]
looks like it went back to the sledgehammer fluid error again https://pastebin.com/9RAwbrQt

**Comment by jbredwards** [comment]
how about [this](https://discordapp.com/channels/@me/785959414632939571/864187382516416572)? Thank you for your patience btw :)

**Comment by jbredwards** [comment]
how about [this](https://cdn.discordapp.com/attachments/785959414632939571/864187382206169168/Fluidlogged-API-v1.5.1-mc1.12.2.jar)? Also I may have deleted my previous reply cause wrong link

**Comment by xemnes** [comment]
thanks, i will test later this evening as i am working late tonight.

**Comment by xemnes** [comment]
i completely forgot about this, im sorry. i will be testing this shortly.

**Comment by xemnes** [comment]
the server booted up! i think thats fixed now. thank you! will report any further issues if i find any.

**Comment by xemnes** [comment]
never mind, im an idiot... i didnt add the mod into the mods folder, instead i put it in a subfolder without realising. sadly it crashes again :( https://pastebin.com/qdArtKPB though this time doesnt seem to be because of sledgehammer

**Comment by jbredwards** [comment]
maybe fixed in v1.5.2. Re-open if that isn't the case. I feel so bad that I can't replicate the sledgehammer issues :(

**Comment by xemnes** [comment]
thanks, i will test it tomorrow hopefully. and its not your fault, i wish theres more i could do to help to be honest. one thing that is notable to mention is that i use mohist on my server which is a spigot/forge hybrid

**Comment by xemnes** [comment]
still crashing sadly, https://pastebin.com/kAgjZiSK perhaps its because im using mixin compat 0.8 or mohist?
edit: wasnt able to reopen.

**Comment by jbredwards** [comment]
I just had kind of an eureka moment, here's the [fix](https://github.com/jbredwards/Fluidlogged-API/files/6901780/extract.me.zip)! Sending it to you before I release the next update on curse because you've had to wait long enough! :)

**Comment by xemnes** [comment]
happy to say it works! thank you :D
