### ISSUE TITLE
以特定形式放置红石中继器产生bug,最终游戏崩溃。RedstoneRepeater stabilization triggers game crash.

### ISSUE THREAD

**Issue by V4444life** [jbredwards/Fluidlogged-API#243]
**Describe the bug**
游戏崩溃。
稳定复现的症状：在forge2860或者cleanroom0.3.0下，仅有Fluidloggedapi3.0.4一个模组，并排放置两个方向平行的红石中继器，手中的红石中继器数量异常，此时破坏红石中继器会导致游戏崩溃。
在创造模式，触发后也会让物品数量减少。
两个红石中继器方向垂直不会导致此问题。
Game crashes.
Stable recurrence: under forge2860 or cleanroom0.3.0, Fluidloggedapi3.0.4 only, placing two RedstoneRepeater side by side in parallel directions, with an abnormal number of RedstoneRepeater in hand, destroying a RedstoneRepeater at this point causes the game to crash.
In Creative Mode, triggering it will also cause the number of items to decrease.
Two RedstoneRepeater oriented perpendicular to each other will not cause this issue.

**To Reproduce**
1. 并排放置两个方向平行的红石中继器。
2. 发现物品栏红石中继器数量异常变化。
3. 破坏刚刚放置的红石中继器。
4. 游戏崩溃。

1. Place two RedstoneRepeater side by side in parallel directions.
2. Discover an unusual change in the number of RedstoneRepeater in the Item Bar.
3. Destroy the RedstoneRepeater you just placed.
4. Game crashes.

**Screenshots**
我截了图，但是点击上传附件的标志却无法上传附件。
文字描述：
情况1：【红石中继器】紧贴着【红石中继器】方向相同。
情况2：【红石中继器】紧贴着【红石中继器】方向相反。
I've taken a screenshot, but clicking on the upload attachment logo doesn't upload the attachment.
Text description:
Case 1: [RedstoneRepeater] is next to [RedstoneRepeater] in the same direction.
Case 2: [RedstoneRepeater] is next to [RedstoneRepeater] in the opposite direction.

**Logs**
If you have access to any logs, please link them [here](https://gist.github.com/).
我无法上传附件。不过这个问题可以稳定的触发，所以问题不大。
I can't upload attachments. The issue can be triggered steadily though, so it's not a big problem.

**Additional context**
Add any other context about the problem here, this may include mods, plugins, etc.
其他症状：
1有一次在装有其他模组时，大量的流动的水从高处倾泻而下时，可能会崩溃，具体症状是：当玩家看向那些正在向下流淌的水，游戏崩溃。重新进入世界后只要不去看那些水就不会崩溃，一旦视角转过去就崩溃。无法稳定复现。
2在装有其他模组时，在触发物品数量异常变化后，调节中继器的挡位也会导致游戏崩溃。但是因为装载了太多模组无法确定具体是什么模组造成的。
物品数量异常变化也会影响其他物品，导致物品消失。无法稳定复现。
Other issues:
1Once, with other modules installed, a large amount of flowing water pouring down from a high place may crash, specifically: when the player looks at the water that is flowing downward, the game crashes. After re-entering the world it doesn't crash as long as you don't look at that water, once the viewpoint is turned around it crashes. Cannot be reproduced stably.
2Adjusting the RedstoneRepeater's stops after triggering an abnormal change in the number of items when other modules are loaded also causes the game to crash. However, because too many modules are loaded it is not possible to determine exactly what module is causing this.
Anomalous changes in item count can also affect other items, causing them to disappear. It cannot be reproduced stably.

**Comment by V4444life** [comment]
今日的游玩，cleanroom0.3.0，只安装Fluidloggedapi3.0.4
稳定复现：开启F3后准星指向并排放置的红石中继器，游戏就会崩溃。
稳定复现：在连续放置并排的红石中继器后，并排下一个放置的任意方块会减少手中物品数目，就像红石中继器的数量减少一样。
稳定复现：大量流动的水导致性能下降最终游戏崩溃。在高空建造一个平台,覆盖上了流动的水，然后移除下方的平台，大面积不同状态的水向下流淌，游戏性能下降，最终游戏崩溃。
Today's playthrough, cleanroom 0.3.0, only Fluidloggedapi 3.0.4 
Stable Reproduction: after turning on F3 with the crosshair pointing at side-by-side placed redstonerepeaters, the game crashes.
Stable Reproduction: After placing successive side-by-side redstone repeaters, the next placed arbitrary block side-by-side reduces the number of items in hand, just as the number of redstone repeaters is reduced.
Stable Reproduction: Large amounts of flowing water cause performance to drop and eventually the game crashes. Build a platform high in the sky, cover it with flowing water, then remove the platform below, a large area of water in different states flows downward, the game's performance drops and eventually the game crashes.

**Comment by jbredwards** [comment]
Fixed in v3.0.5!

**Comment by V4444life** [comment]
@jbredwards 
Nice
但是大量流动的水下落导致性能下降最终游戏崩溃这个问题没有完全解决。我还是可以复现这个崩溃。
我傻逼了，我才想到我可以直接把报错粘贴在这里(x_x)
这是崩溃报告
Nice
But the issue of a large amount of flowing water falling causing performance to drop and eventually the game to crash is not fully resolved. I can still reproduce this crash.
Silly me, it just occurred to me that I could just paste the error report here (x_x)
Here's the crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (cleanroom-0.3.0-alpha.jar)
  Fluidlogged API Plugin (Fluidlogged-API-v3.0.5-mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 2025-03-27 13:16
Description: Tesselating block in world

java.lang.UnsupportedOperationException: Cannot get level from empty FluidState!
	at git.jbredwards.fluidlogged_api.api.util.FluidState$EmptyFluidState.getLevel(FluidState.java:771)
	at git.jbredwards.fluidlogged_api.api.util.FluidState.getWrappedLevel(FluidState.java:395)
	at git.jbredwards.fluidlogged_api.api.fluid.IFluidloggableFluid.isReplaceableByOther(IFluidloggableFluid.java:64)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.util.ISpecializedFluidNeighborInfo.isReplaceableI(ISpecializedFluidNeighborInfo.java:127)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.canFlowOrReplaceable(FluidExtendedStateHandler.java:172)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.getHorizontalConnection(FluidExtendedStateHandler.java:161)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.getFluidHeightForRender(FluidExtendedStateHandler.java:120)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.getExtendedState(FluidExtendedStateHandler.java:61)
	at git.jbredwards.fluidlogged_api.mod.asm.plugins.vanilla.block.PluginBlockLiquid$Hooks.getLiquidExtendedState(PluginBlockLiquid.java:430)
	at net.minecraft.block.BlockLiquid.getExtendedState(BlockLiquid.java)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:122)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:50)
	at java.base/java.lang.Thread.run(Thread.java:1583)
No Mixin Metadata is found in the Stacktrace.


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at git.jbredwards.fluidlogged_api.api.util.FluidState$EmptyFluidState.getLevel(FluidState.java:771)
	at git.jbredwards.fluidlogged_api.api.util.FluidState.getWrappedLevel(FluidState.java:395)
	at git.jbredwards.fluidlogged_api.api.fluid.IFluidloggableFluid.isReplaceableByOther(IFluidloggableFluid.java:64)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.util.ISpecializedFluidNeighborInfo.isReplaceableI(ISpecializedFluidNeighborInfo.java:127)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.canFlowOrReplaceable(FluidExtendedStateHandler.java:172)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.getHorizontalConnection(FluidExtendedStateHandler.java:161)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.getFluidHeightForRender(FluidExtendedStateHandler.java:120)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.getExtendedState(FluidExtendedStateHandler.java:61)
	at git.jbredwards.fluidlogged_api.mod.asm.plugins.vanilla.block.PluginBlockLiquid$Hooks.getLiquidExtendedState(PluginBlockLiquid.java:430)
	at net.minecraft.block.BlockLiquid.getExtendedState(BlockLiquid.java)

-- Block being tesselated --
Details:
	Block type: ID #9 (tile.water // net.minecraft.block.BlockStaticLiquid // minecraft:water)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-1459,203,-132), Chunk: (at 13,12,12 in -92,-9; contains blocks -1472,0,-144 to -1457,255,-129), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)

**Comment by jbredwards** [comment]
Fixed in v3.0.6! Let me know if you find any other crashes! :)

**Comment by V4444life** [comment]
@jbredwards 
是的，我还是可以稳定重现游戏崩溃。
只是在高空放置一些方块和流动的水，让水自由的流动下去，fps从250降低至30然后游戏崩溃。
这是崩溃报告
Yes, I can still reproduce the game crash consistently.
Just placing some blocks and flowing water high in the air and letting the water flow freely down, the fps drops from 250 to 30 then the game crashes.
Here's the crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (cleanroom-0.3.0-alpha.jar)
  Fluidlogged API Plugin (Fluidlogged-API-v3.0.6-mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 2025-04-08 22:35
Description: Tesselating block in world

java.lang.UnsupportedOperationException: Cannot get level from empty FluidState!
	at git.jbredwards.fluidlogged_api.api.util.FluidState$EmptyFluidState.getLevel(FluidState.java:771)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.util.ISpecializedFluidNeighborInfo$Vanilla.getEffectiveQuantaI(ISpecializedFluidNeighborInfo.java:67)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.util.ISpecializedFluidNeighborInfo.getEffectiveQuanta(ISpecializedFluidNeighborInfo.java:172)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidFlowHandler.getFlowVec(FluidFlowHandler.java:56)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidFlowHandler.getFlowAngle(FluidFlowHandler.java:47)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.getExtendedState(FluidExtendedStateHandler.java:110)
	at git.jbredwards.fluidlogged_api.mod.asm.plugins.vanilla.block.PluginBlockLiquid$Hooks.getLiquidExtendedState(PluginBlockLiquid.java:430)
	at net.minecraft.block.BlockLiquid.getExtendedState(BlockLiquid.java)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:122)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:50)
	at java.base/java.lang.Thread.run(Thread.java:1583)
No Mixin Metadata is found in the Stacktrace.


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at git.jbredwards.fluidlogged_api.api.util.FluidState$EmptyFluidState.getLevel(FluidState.java:771)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.util.ISpecializedFluidNeighborInfo$Vanilla.getEffectiveQuantaI(ISpecializedFluidNeighborInfo.java:67)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.util.ISpecializedFluidNeighborInfo.getEffectiveQuanta(ISpecializedFluidNeighborInfo.java:172)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidFlowHandler.getFlowVec(FluidFlowHandler.java:56)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidFlowHandler.getFlowAngle(FluidFlowHandler.java:47)
	at git.jbredwards.fluidlogged_api.mod.common.fluid.handler.FluidExtendedStateHandler.getExtendedState(FluidExtendedStateHandler.java:110)
	at git.jbredwards.fluidlogged_api.mod.asm.plugins.vanilla.block.PluginBlockLiquid$Hooks.getLiquidExtendedState(PluginBlockLiquid.java:430)
	at net.minecraft.block.BlockLiquid.getExtendedState(BlockLiquid.java)

-- Block being tesselated --
Details:
	Block type: ID #9 (tile.water // net.minecraft.block.BlockStaticLiquid // minecraft:water)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-128,62,-14), Chunk: (at 0,3,2 in -8,-1; contains blocks -128,0,-16 to -113,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)

**Comment by V4444life** [comment]
@jbredwards 
我终于可以把文件传上来了
还是可以稳定触发游戏帧数骤降（250fps->30fps）最终游戏崩溃
附加一张稳定触发崩溃的建造方式截图
触发方式就是在这些石头上的放置几格水
I was finally able to upload the file
It's still possible to stably trigger a sudden drop in game framerate (250fps -> 30fps) and eventually a game crash
Attach a screenshot of the build that stabilizes trigger crashes
Triggered by placing a few squares of water on top of these rocks.

![Image](https://github.com/user-attachments/assets/bbba5531-e971-427c-9ee9-8efe6374d8e7)

[minecraft-exported-crash-info-2025-04-08T22-59-07.zip](https://github.com/user-attachments/files/19651998/minecraft-exported-crash-info-2025-04-08T22-59-07.zip)

**Comment by jbredwards** [comment]
Fixed in v3.1.0!
