### ISSUE TITLE
Weird transition between water and other water fluids

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Fluidlogged-API#44]
### The issue
Water and other `Material.WATER` fluids have a visible border between them:
![2022-01-23_15 24 13](https://user-images.githubusercontent.com/71150936/150683568-acf6741c-81d8-468c-9503-66e43e7db8dc.png)
![2022-01-23_15 24 15](https://user-images.githubusercontent.com/71150936/150683578-6bc4f43a-507f-4348-905a-c95f061aa3a4.png)

### To Reproduce
- Install **SimpleDifficulty** for example.
- Place some Purified Water, or _any_ other moded water (**Biomes o' Plenty** Spring Water), alongside vanilla water.
- See :D

### Expected behaviour
No border between fluids:
![2022-01-23_15 26 39](https://user-images.githubusercontent.com/71150936/150683527-0d1c7ce4-1592-447c-9ce2-b2bb572cfb09.png)
![2022-01-23_15 26 35](https://user-images.githubusercontent.com/71150936/150683548-8e804b49-2e8f-4b8e-ad11-cfd4a6f677dc.png)

**Comment by jbredwards** [comment]
This behavior is intentional, however the next version will have a workaround for like-fluids

**Comment by juraj-hrivnak** [comment]
Oh, thank you so much! I appreciate it!

**Comment by jbredwards** [comment]
fixed in v1.7

**Comment by juraj-hrivnak** [comment]
I'm still experiencing this issue. Is there something in the config I should do?
I'm using Fluidlogged-API-v1.7.2.

Edit: Oh, it's an issue on my side.

**Comment by jbredwards** [comment]
>I'm still experiencing this issue. Is there something in the config I should do?

No, other mods have to add the compat themselves, I'll make a pull request for SimpleDifficulty which'll fix the issue

**Comment by juraj-hrivnak** [comment]
Oh, I thought it would be something like that.
That would be awesome. Thank you for the quick response!
